version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-visit-scheduler-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/health_tracking
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - db
    networks:
      - medical_network

  db:
    image: mysql:8.0
    container_name: medical-visit-scheduler-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: health_tracking
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - medical_network

networks:
  medical_network:
    driver: bridge

volumes:
  db-data:
